### ISSUE TITLE
Document the font-end codebase of MDN Web Docs

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#21]
This is currently underway in this project and can be viewed at:
https://mdn.github.io/mdn-fiori/

This will cover(not finite):

## General

* Code style
* Editor configuration

## CSS

* Best practise (cross pollinate with other teams on this)
* Syntax standard for both CSS and SaSS
* Documentation of linting rules we follow

## JavaScript

* Best practise (cross pollinate with other teams on this)
* Syntax standard
* Documentation of linting rules we follow

## HTML

* Best practise (cross pollinate with other teams on this)
* Syntax standard

## Frontend Workflow

* General documentation of the front-end tool chain.

## Components

Common components found in the MDN Web Docs code base with:

1. A live example of the module
2. The required HTML, CSS and JS as applicable

## Tasks

- [ ] Make a back-up of the currently documented work before merging the Storybook PR
- [ ] Create issues for components
- [ ] Define typography
- [ ] Define colour scheme
- [ ] Break components down using Atomic Design principals

**Comment by jmswisher** [comment]
Given the large size estimate, could this issue be converted to an epic, and decomposed into issues of <=5 days each?

**Comment by schalkneethling** [comment]
Yup, that makes total sense.

**Comment by malqinneh** [comment]
@schalkneethling is this issue still applicable or redundant based on the new tasks we added?

**Comment by schalkneethling** [comment]
> @schalkneethling is this issue still applicable or redundant based on the new tasks we added?

Redundant. Closing.
