### ISSUE TITLE
Replace Font-awesome with SVG icons

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#9]
The benefits of switching to a SVG icon system over a icon font system are numerous, for example:

1. Load only the icons you need
2. Faster load time because, see above
3. Smaller overall file size
4. Much crisper on high resolution displays
5. Offers even more design control
6. Predictable and performant
7. As the icons will be inlined, there are no HTTP requests

To stay consistent with the current design, the icons will still be those from the FontAwesome set, but will be inlined SVG instead of an icon font.

Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1451261

## Tasks

* [x] Convert in page icons to SVG icons
* [x] Add titles for SVG icons used a link targets
* [x] Write Jinja helper for custom titles and l10n
* [ ] Replace remainder of icons that needs to be specified as background images in CSS
* [ ] Remove FontAwesome and all related assets.

**Comment by schalkneethling** [comment]
Additional reading: Seriously, Don’t Use Icon Fonts

**Comment by jwhitlock** [comment]
@schalkneethling can this be closed?

**Comment by schalkneethling** [comment]
Indeed it can.
